name: spot-show

services:
  postgres:
    image: postgres:17
    container_name: spot-show-postgres

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: janardan
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotShow

    volumes:
      - spot_show_postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  spot_show_postgres_data:

# postgresql://janardan:postgres@localhost:5432/openpravesh